---
- name: install redir
  apt: name=redir state=present
  when: ansible_distribution == "Ubuntu" 

- name: install EPEL repo
  yum: name=http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: install EPEL repo
  yum: name=http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: install redir
  yum: name=redir state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '6'

- name: install redir
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/redir-2.2.1-7.el6.x86_64.rpm state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '7'

- name: install redir
  yum: name=redir state=present
  when: ansible_distribution == "Fedora"

- name: put redir.rb
  template: src=redir.rb dest=/etc/eye/redir-{{ name }}.rb
  notify: reload eye

- meta: flush_handlers
